spring:
    profiles:
        active:
        - dev

---
server:
    port: 8001
    
spring:
    profiles: dev   #开发环境
    application:
        name: kikro-springcloud-config-emp-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://58.87.86.122:3306/itest
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.earth.model               # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml      

          
eureka:
  client: #客户端注册进eureka服务
    service-url:
     # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-tianjin-Emp-8001
    prefer-ip-address: true #访问路径可以显示IP地址          


info:
  app.name: kikro_project
  company.name: www.aixuexi.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
---
server:
    port: 8001
    
spring:
    profiles: test   #开发环境
    application:
        name: kikro-springcloud-config-emp-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://58.87.86.122:3306/itest
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.earth.model               # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml      

          
eureka:
  client: #客户端注册进eureka服务
    service-url:
     # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-tianjin-Emp-8001
    prefer-ip-address: true #访问路径可以显示IP地址          


info:
  app.name: kikro_project
  company.name: www.aixuexi.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$